# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220dfae9a577c2a1a078f570efeace54f32f09c7be04baf472541065c3a07e4218e";
    path = fetchzip {
      url = "https://github.com/Arwalk/zig-protobuf/archive/a2762e39138ca23b8e380edb535f85578f159d1c.tar.gz";
      hash = "sha256-Nr+pEC0E9gthjdWo4R3TdKl14tWyo9cTs0ZdLIdAnYM=";
    };
  }
]
