name: release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  x86_64-darwin:
    name: Build x86_64-darwin
    runs-on: macos-13
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build .#default
      - name: Show hash
        run: shasum -a 256 ./result/lib/compact_execlog*
  aarch64-darwin:
    name: Build aarch64-darwin
    runs-on: macos-14
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build .#default
      - name: Show hash
        run: shasum -a 256 ./result/lib/compact_execlog*
  x86_64-linux:
    name: Build x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build .#default
      - name: Show hash
        run: shasum -a 256 ./result/lib/compact_execlog*
  x86_64-linux-gcc4:
    name: Build x86_64-linux-gcc4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build .#default-gcc4
      - name: Show hash
        run: shasum -a 256 ./result/lib/compact_execlog*        
